'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const html = read('options/options.html');
const js = read('options/options.js');
const popup = read('popup/popup.js');
assert.match(html,/data-tab="services"[^>]*>対応サービス</);
assert.match(html,/data-tab="backup"[^>]*>バックアップ・復元</);
assert.match(html,/data-tab="data"[^>]*>保存データ</);
assert.match(html,/id="panel-services"[\s\S]*id="xSplitMedia"[\s\S]*id="threadsTokenInput"/);
assert.match(html,/id="panel-backup"[\s\S]*id="exportBackupBtn"[\s\S]*id="backupDropZone"/);
assert.match(html,/id="panel-data"[\s\S]*id="managedAccounts"[\s\S]*id="resetAllBtn"/);
assert.doesNotMatch(html,/id="supportedServices"/);
assert.match(html,/Threadsトークン 取トーくんを開く/);
assert.match(html,/トークンを保存/);
assert.match(html,/トークンを削除/);
assert.match(html,/共有PCでの利用にはご注意ください/);
assert.match(html,/id="threadsTokenInput"[^>]*type="text"/);
assert.match(js,/＊＊＊＊＊＊＊＊（保存済み）/);
assert.match(js,/トークンを削除しました。/);
assert.match(js,/smz_options_active_tab_v1/);
assert.match(js,/tab === 'data'[\s\S]*loadAccountsInto/);
assert.match(popup,/ZIP保存を停止しています/);
assert.match(popup,/作成途中のZIPを削除しています/);
assert.match(popup,/scannedPosts/);
console.log('PASS settings tabs: services first, backup/data separated, last tab remembered, ZIP-stop status in main panel, API scan counter visible');
